image: docker:24.0.6

include:
  - template: Security/Secret-Detection.gitlab-ci.yml

variables:
  CI_USER: $GITLAB_USER
  CI_TOKEN: $GITLAB_USER_TOKEN_HIVEER
  GIT_DEPTH: 100

stages:
  - test
  - build

# 判断是不是正确的project，正确的branch，以及是不是forked repo过来的MR
.if-starhub-main-original-repo: &if-starhub-main-original-repo
  if: '$CI_COMMIT_REF_NAME == "starhub-main" && $CI_PROJECT_ID == "32" && $CI_MERGE_REQUEST_SOURCE_PROJECT_ID == null'

# for production docker image build
# e.g., v1.0.0
#
.if-production-tag-build: &if-production-tag-build
  if: '$CI_PROJECT_ID == "32" && $CI_COMMIT_TAG =~ /^v(\d+(?:\.\d+.\d+)*)$/'

production-tag-build:
  stage: build
  services:
    - docker:24.0.6-dind
  tags:
    - linux-medium-amd64
  rules:
    - <<: *if-production-tag-build
  variables:
    IMAGE_TAG: $CI_REGISTRY_IMAGE:$CI_COMMIT_TAG
  script:
    - docker login $CI_REGISTRY -u $CI_USER -p $CI_TOKEN
    - docker build -t $IMAGE_TAG .
    - docker push $IMAGE_TAG

starhub-build:
  stage: build
  services:
    - docker:24.0.6-dind
  tags:
    - linux-medium-amd64
  rules:
    - <<: *if-starhub-main-original-repo
  variables:
    IMAGE_TAG: $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG
  script:
    - docker login $CI_REGISTRY -u $CI_USER -p $CI_TOKEN
    - docker build -t $IMAGE_TAG .
    - docker push $IMAGE_TAG