version: '2.4'

services:
  nginx:
    image: opencsg-registry.cn-beijing.cr.aliyuncs.com/public/nginx:latest
    ports:
      - ${SERVER_PORT}:${SERVER_PORT}
      - ${SERVER_CASDOOR_PORT}:${SERVER_CASDOOR_PORT}
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/logs:/var/log/nginx
      - ./nginx/tmpdata:/var/nginx/client_body_temp
    privileged: true
    networks:
      - opencsg
    restart: always

  redis:
    image: opencsg-registry.cn-beijing.cr.aliyuncs.com/opencsg_public/redis:7.2.5
    ports:
      - "6379:6379"
    volumes:
      - redis:/data
    networks:
      - opencsg
    healthcheck:
      test: redis-cli ping
      interval: 1s
      timeout: 3s
      retries: 30

  coredns:
    image: opencsg-registry.cn-beijing.cr.aliyuncs.com/opencsg_public/coredns/coredns:1.11.1
    ports:
      - "1053:53/udp"
      - "1053:53/tcp"
    command: "-conf /root/Corefile"
    volumes:
      - ./coredns/:/root/:r
    privileged: true
    networks:
      opencsg:
        ipv4_address: 172.25.0.25

  registry:
    image: opencsg-registry.cn-beijing.cr.aliyuncs.com/opencsg_public/registry:2
    ports:
      - "5000:5000"
    volumes:
      - registry:/var/lib/registry
      - ./auth:/auth
    networks:
      - opencsg
    environment:
      REGISTRY_AUTH: "htpasswd"
      REGISTRY_AUTH_HTPASSWD_REALM: "Registry Realm"
      REGISTRY_AUTH_HTPASSWD_PATH: "/auth/htpasswd"

  postgres:
    image: opencsg-registry.cn-beijing.cr.aliyuncs.com/opencsg_public/gradescope/postgresql-multiple-databases:14.4
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "sdfa23Sh!322"
      POSTGRES_MULTIPLE_DATABASES: "starhub_server,gitea,casdoor"
    ports:
      - "5433:5432"
    networks:
      - opencsg
    healthcheck:
      test: pg_isready -U postgres -h 127.0.0.1
      interval: 5s
    volumes:
      - pgdata:/var/lib/postgresql/data

  csghub_portal:
    image: opencsg-registry.cn-beijing.cr.aliyuncs.com/opencsg_public/csghub_portal:latest
    restart: always
    command: >
      bash -c "bundle exec rails assets:precompile && bundle exec rails db:create && bundle exec rails db:migrate && bundle exec rails db:seed && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - ./log:/myapp/log
    environment:
      DATABASE_URL: postgresql://postgres:sdfa23Sh!322@postgres:5432/open_portal_db
      ASSET_HOST: http://127.0.0.1:3000
      RAILS_MASTER_KEY: 64f15f995b044427e43fe4897370fd66
      RAILS_SERVE_STATIC_FILES: 'false'
      STARHUB_BASE_URL: http://${SERVER_DOMAIN}:${SERVER_PORT}
      STARHUB_INNER_BASE_URL: http://csghub_server:8080
      LOGIN_URL: http://${SERVER_DOMAIN}:${SERVER_CASDOOR_PORT}/login/oauth/authorize?client_id=d554744494d93c21a6ab&response_type=code&redirect_uri=http://${SERVER_DOMAIN}:${SERVER_PORT}/api/v1/callback/casdoor&scope=read&state=casdoor
      SIGNUP_URL: http://${SERVER_DOMAIN}:${SERVER_CASDOOR_PORT}/signup/CSGHub
      OIDC_IDENTIFIER: d554744494d93c21a6ab
      OIDC_SECRET: 2d942276879382c66363ef6303e0d66d37e5d98d
      OIDC_REDIRECT_URI: http://${SERVER_DOMAIN}:${SERVER_PORT}/oidc/callback
      OIDC_AUTHORIZATION_ENDPOINT: http://${SERVER_DOMAIN}:${SERVER_CASDOOR_PORT}/login/oauth/authorize
      OIDC_TOKEN_ENDPOINT: http://${SERVER_DOMAIN}:${SERVER_CASDOOR_PORT}/api/login/oauth/access_token
      OIDC_USERINFO_ENDPOINT: http://${SERVER_DOMAIN}:${SERVER_CASDOOR_PORT}/api/userinfo
      STARHUB_TOKEN: ${HUB_SERVER_API_TOKEN}
      BUCKET_NAME: opencsg-portal-storage
      ENDPOINT: http://${SERVER_DOMAIN}:9000
      ACCESS_ID: admin
      ACCESS_SECRET: Password_123
      REGION: cn-beijing
      ON_PREMISE: false
      FORCE_PATH_STYLE: true
    ports:
      - "3000:3000"
    networks:
      - opencsg
    depends_on:
      - postgres

  csghub_server:
    image: opencsg-registry.cn-beijing.cr.aliyuncs.com/opencsg_public/csghub_server:latest
    depends_on:
      - postgres
      - gitea
    environment:
      STARHUB_SERVER_GITSERVER_URL: http://${SERVER_DOMAIN}:${SERVER_PORT}/gitserver
      STARHUB_SERVER_FRONTEND_URL: http://${SERVER_DOMAIN}:${SERVER_PORT}
      STARHUB_DATABASE_DSN: postgresql://postgres:sdfa23Sh!322@postgres:5432/starhub_server?sslmode=disable
      STARHUB_DATABASE_TIMEZONE: Asia/Shanghai
      STARHUB_SERVER_REDIS_ENDPOINT: redis:6379
      STARHUB_SERVER_GITSERVER_HOST: http://gitea:3001
      STARHUB_SERVER_GITSERVER_USERNAME: root
      STARHUB_SERVER_GITSERVER_PASSWORD: password123
      STARHUB_SERVER_GITSERVER_WEBHOOK_URL: http://csghub_server:8080/api/v1/callback/git
      GITEA_USERNAME: root
      GITEA_PASSWORD: password123
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: sdfa23Sh!322
      POSTGRES_DB: starhub_server
      GIN_MODE: release
      STARHUB_SERVER_API_TOKEN: ${HUB_SERVER_API_TOKEN}
      STARHUB_SERVER_S3_ACCESS_KEY_ID: admin
      STARHUB_SERVER_S3_ACCESS_KEY_SECRET: Password_123
      STARHUB_SERVER_S3_ENDPOINT: ${SERVER_DOMAIN}:9000 # used to generate download links for lfs files
      STARHUB_SERVER_S3_BUCKET: opencsg-server-lfs
      STARHUB_SERVER_S3_REGION: cn-beijing
      STARHUB_SERVER_SPACE_BUILDER_ENDPOINT: http://space_builder:8080
      STARHUB_SERVER_SPACE_RUNNER_ENDPOINT: http://csghub_server_runner:8082
      STARHUB_SERVER_PUBLIC_ROOT_DOMAIN: ""
      STARHUB_SERVER_INTERNAL_ROOT_DOMAIN: ${SPACE_APP_NS}.${SPACE_APP_INTERNAL_DOMAIN}:${SPACE_APP_INTERNAL_DOMAIN_PORT} #space.lwf.internal:30446
      STARHUB_SERVER_MODEL_DOWNLOAD_ENDPOINT: http://${SERVER_DOMAIN}:${SERVER_PORT}
      STARHUB_SERVER_SAAS: false
      STARHUB_SERVER_MIRRORSERVER_ENABLE: false
      STARHUB_SERVER_CASDOOR_CLIENT_ID: d554744494d93c21a6ab
      STARHUB_SERVER_CASDOOR_CLIENT_SECRET: 2d942276879382c66363ef6303e0d66d37e5d98d
      STARHUB_SERVER_CASDOOR_ENDPOINT: http://${SERVER_DOMAIN}:${SERVER_CASDOOR_PORT}
      STARHUB_SERVER_CASDOOR_CERTIFICATE: /starhub-bin/casdoor/token_jwt_key.pem
      STARHUB_SERVER_CASDOOR_ORGANIZATION_NAME: OpenCSG
      STARHUB_SERVER_CASDOOR_APPLICATION_NAME: CSGHub
      STARHUB_JWT_SIGNING_KEY: e2kk6awudc3620ed9a
      OPENCSG_ACCOUNTING_NATS_URL: nats://natsadmin:gALqqbP6SpftVdFzrU2URJ8k1G@natsmaster:4222
      OPENCSG_ACCOUNTING_SERVER_HOST: http://account_server
      OPENCSG_ACCOUNTING_SERVER_PORT: 8086
      OPENCSG_USER_SERVER_HOST: http://user_server
      OPENCSG_USER_SERVER_PORT: 8088
      STARHUB_SERVER_S3_ENABLE_SSL: false
      STARHUB_SERVER_PUBLIC_DOMAIN: http://${SERVER_DOMAIN}:${SERVER_PORT}
    ports:
      - "8080:8080"
    restart: always
    networks:
      - opencsg
    volumes:
      - ./gitlog:/starhub-bin/logs:r

  csghub_server_runner:
    image: opencsg-registry.cn-beijing.cr.aliyuncs.com/opencsg_public/csghub_server:latest
    entrypoint:
      - /starhub-bin/starhub
      - deploy
      - runner
    environment:
      STARHUB_DATABASE_DSN: postgresql://postgres:sdfa23Sh!322@postgres:5432/starhub_server?sslmode=disable
      STARHUB_DATABASE_TIMEZONE: Asia/Shanghai
      STARHUB_SERVER_DOCKER_REG_BASE: ${DOCKER_REGISTRY_SERVER}/${DOCKER_REGISTRY_NS}/
      STARHUB_SERVER_INTERNAL_ROOT_DOMAIN: ${SPACE_APP_NS}.${SPACE_APP_INTERNAL_DOMAIN}:${SPACE_APP_INTERNAL_DOMAIN_PORT}
      STARHUB_SERVER_DOCKER_IMAGE_PULL_SECRET: ${DOCKER_REGISTRY_SECRET} #space-registry-credential
    ports:
      - "8082:8082"
    restart: always
    networks:
      - opencsg
    dns:
      - "172.25.0.25"
    volumes:
      - ./.kube:/root/.kube:r

  csghub_server_proxy:
    image: opencsg-registry.cn-beijing.cr.aliyuncs.com/opencsg_public/csghub_server:latest
    entrypoint:
      - /starhub-bin/starhub
      - start
      - rproxy
    environment:
      STARHUB_SERVER_SPACE_SESSION_SECRET_KEY: c8f771f2a178089b99172cbbd7e3b01d
      STARHUB_DATABASE_DSN: postgresql://postgres:sdfa23Sh!322@postgres:5432/starhub_server?sslmode=disable
      STARHUB_DATABASE_TIMEZONE: Asia/Shanghai
      STARHUB_SERVER_GITSERVER_HOST: http://gitea:3001
      STARHUB_SERVER_GITSERVER_URL: http://gitea:3001
      STARHUB_SERVER_GITSERVER_USERNAME: root
      STARHUB_SERVER_GITSERVER_PASSWORD: password123
      STARHUB_SERVER_GITSERVER_WEBHOOK_URL: http://csghub_server:8080/api/v1/callback/git
      STARHUB_SERVER_INTERNAL_ROOT_DOMAIN: ${SPACE_APP_NS}.${SPACE_APP_INTERNAL_DOMAIN}:${SPACE_APP_INTERNAL_DOMAIN_PORT}
      STARHUB_SERVER_SAAS: false
      STARHUB_SERVER_MIRRORSERVER_ENABLE: false
      STARHUB_JWT_SIGNING_KEY: e2kk6awudc3620ed9a
    ports:
      - "8083:8083"
    networks:
      - opencsg
    dns:
      - "172.25.0.25"
    restart: always

  space_builder:
    image: opencsg-registry.cn-beijing.cr.aliyuncs.com/opencsg_public/csghub-space-builder:latest
    environment:
      - REDIS_ENDPOINT=redis:6379
      - SPACE_DATA_PATH=/opt/data
      - DOCKER_HOST=${SPACE_BUILDER_SERVER}
      - REGISTRY_ADDRESS=${DOCKER_REGISTRY_SERVER}
      - REGISTRY_USERNAME=${DOCKER_REGISTRY_USERNAME}
      - REGISTRY_PASSWORD=${DOCKER_REGISTRY_PASSWD}
      - REGISTRY_NAMESPACE=${DOCKER_REGISTRY_NS} #opencsg_space
    ports:
      - "8085:8080"
    restart: always
    networks:
      - opencsg
    volumes:
      - ./space_data:/opt/data:rw

  gitea:
    image: opencsg-registry.cn-beijing.cr.aliyuncs.com/opencsg_public/csghub_git:v0.7.0
    depends_on:
      - postgres
    environment:
      - GITEA_ROOT_URL=http://${SERVER_DOMAIN}:${SERVER_PORT}/gitserver
      - GITEA_DOMAIN=${SERVER_DOMAIN}:${SERVER_PORT}/gitserver
      - GITEA_SSH_DOMAIN=${SERVER_DOMAIN}
      - GITEA_HTTP_PORT=3001
      - GITEA_SSH_LISTEN_PORT=2222
      - GITEA_ADMIN_USER=root
      - GITEA_ADMIN_PASSWORD=password123
      - GITEA_ADMIN_EMAIL=root@opencsg.com
      - GITEA_DATABASE_TYPE=postgres
      - GITEA_DATABASE_HOST=postgres
      - GITEA_DATABASE_PORT_NUMBER=5432
      - GITEA_DATABASE_NAME=gitea
      - GITEA_DATABASE_USERNAME=postgres
      - GITEA_DATABASE_PASSWORD=sdfa23Sh!322
      - GITEA_DATABASE_SSL_MODE=disable
      - GITEA_APP_NAME=git
      - GITEA_SMTP_ENABLED=false
      - BITNAMI_DEBUG=true
      - GITEA_LFS_START_SERVER=true
      - GITEA_LFS_ROOT_PATH=/opt/bitnami/gitea/data/lfs
      - GITEA_LFS_STORAGE_TYPE=minio
      - GITEA_LFS_MINIO_ACCESS_KEY_ID=admin
      - GITEA_LFS_MINIO_SECRET_ACCESS_KEY=Password_123
      - GITEA_LFS_MINIO_ENDPOINT=minio:9000
      - GITEA_LFS_MINIO_BUCKET=opencsg-server-lfs
      - GITEA_LFS_MINIO_LOCATION=cn-beijing
      - GITEA_LFS_MINIO_USE_SSL=false
      - GITEA_SERVICE_DEFAULT_ALLOW_CREATE_ORGANIZATION=true
      - GITEA_SERVICE_DISABLE_REGISTRATION=false
      - GITEA_LOG_MODE=file
      - GITEA_LOG_ROOT_PATH=/bitnami/logs
      - GITEA_GIT_EXTRA_HEADER=true
    ports:
      - "3001:3001"
      - "2222:2222"
    healthcheck:
      test: curl -fSs 127.0.0.1:3001/api/healthz || exit 1
      interval: 5s
      timeout: 10s
      retries: 3
    networks:
      - opencsg
    privileged: true
    restart: always
    volumes:
      - ./gitdata:/bitnami/gitea
      - ./gitlog:/bitnami/logs

  minio:
    image: opencsg-registry.cn-beijing.cr.aliyuncs.com/opencsg_public/bitnami/minio:2023
    ports:
      - "9000:9000" # api
      - "9001:9001" # console
    environment:
      MINIO_ROOT_USER: admin
      MINIO_ROOT_PASSWORD: Password_123
      MINIO_DEFAULT_BUCKETS: opencsg-server-lfs:public,opencsg-portal-storage:public
      MINIO_SCHEME: http
    volumes:
      - minio_data:/bitnami/minio/data
    networks:
      - opencsg

  natsmaster:
    image: opencsg-registry.cn-beijing.cr.aliyuncs.com/opencsg_public/csghub_nats:2.10.16
    ports:
      - "4222:4222" # api
      - "6222:6222" # cluster
      - "8222:8222" # monitor
    restart: always
    volumes:
      - ./nats/nats-server.conf:/nats-server.conf
      - ./nats/jetstream:/data/jetstream
    networks:
      - opencsg

  account_server:
    image: opencsg-registry.cn-beijing.cr.aliyuncs.com/opencsg_public/csghub_server:latest
    entrypoint:
      - /starhub-bin/starhub
      - accounting
      - launch
    depends_on:
      - natsmaster
    environment:
      STARHUB_SERVER_API_TOKEN: ${HUB_SERVER_API_TOKEN}
      STARHUB_DATABASE_DSN: postgresql://postgres:sdfa23Sh!322@postgres:5432/starhub_server?sslmode=disable
      OPENCSG_ACCOUNTING_SERVER_PORT: 8086
      OPENCSG_ACCOUNTING_NATS_URL: nats://natsadmin:gALqqbP6SpftVdFzrU2URJ8k1G@natsmaster:4222
      OPENCSG_ACCOUNTING_FEE_EVENT_SUBJECT: "accounting.fee.>"
      OPENCSG_ACCOUNTING_NOTIFY_NOBALANCE_SUBJECT: "accounting.notify.nobalance"
      OPENCSG_ACCOUNTING_MSG_FETCH_TIMEOUTINSEC: 5
      OPENCSG_ACCOUNTING_CHARGING_ENABLE: true
      GIN_MODE: release
    ports:
      - "8086:8086"
    restart: always
    networks:
      - opencsg

  user_server:
    image: opencsg-registry.cn-beijing.cr.aliyuncs.com/opencsg_public/csghub_server:latest
    entrypoint:
      - /starhub-bin/starhub
      - user
      - launch
    depends_on:
      - postgres
      - gitea
    environment:
      STARHUB_SERVER_API_TOKEN: ${HUB_SERVER_API_TOKEN}
      STARHUB_DATABASE_DSN: postgresql://postgres:sdfa23Sh!322@postgres:5432/starhub_server?sslmode=disable
      STARHUB_DATABASE_TIMEZONE: Asia/Shanghai
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: sdfa23Sh!322
      POSTGRES_DB: starhub_server
      STARHUB_SERVER_GITSERVER_HOST: http://gitea:3001
      STARHUB_SERVER_GITSERVER_USERNAME: root
      STARHUB_SERVER_GITSERVER_PASSWORD: password123
      STARHUB_SERVER_CASDOOR_CLIENT_ID: d554744494d93c21a6ab
      STARHUB_SERVER_CASDOOR_CLIENT_SECRET: 2d942276879382c66363ef6303e0d66d37e5d98d
      STARHUB_SERVER_CASDOOR_ENDPOINT: http://${SERVER_DOMAIN}:${SERVER_CASDOOR_PORT}
      STARHUB_SERVER_CASDOOR_CERTIFICATE: /starhub-bin/casdoor/token_jwt_key.pem
      STARHUB_SERVER_CASDOOR_ORGANIZATION_NAME: OpenCSG
      STARHUB_SERVER_CASDOOR_APPLICATION_NAME: CSGHub
      STARHUB_JWT_SIGNING_KEY: e2kk6awudc3620ed9a
      OPENCSG_USER_SERVER_PORT: 8088
      OPENCSG_USER_SERVER_SIGNIN_SUCCESS_REDIRECT_URL: http://${SERVER_DOMAIN}:${SERVER_PORT}/server/callback
    ports:
      - "8088:8088"
    restart: always
    networks:
      - opencsg
    volumes:
      - ./casdoor:/starhub-bin/casdoor:r

  casdoor:
    restart: always
    image: opencsg-registry.cn-beijing.cr.aliyuncs.com/opencsg_public/casbin/casdoor:v1.571.0
    ports:
      - "8087:8000"
    depends_on:
      - postgres
    networks:
      - opencsg
    environment:
      RUNNING_IN_DOCKER: "true"
    volumes:
      - ./casdoor/conf:/conf/

  server_proxy_nginx:
    image: opencsg-registry.cn-beijing.cr.aliyuncs.com/public/nginx:latest
    ports:
      - "8090:80"
    volumes:
      - ./rproxy_nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./rproxy_nginx/logs:/var/log/nginx
    privileged: true
    networks:
      opencsg:
        ipv4_address: 172.25.0.26
    restart: always

networks:
  opencsg:
    ipam:
      driver: default
      config:
        - subnet: "172.25.0.0/16"

volumes:
  redis:
    driver: local
  minio_data:
    driver: local
  pgdata:
    driver: local
  registry:
    driver: local
